#include<math.h>
#include "EngineBase/Vector3.cpp"
#include "EngineBase/Quaternion.cpp"
#include "EngineBase/Camera.cpp"
#include "EngineBase/GameObject.cpp"
#include "EngineBase/LookupTables.cpp"
#include "EngineBase/Mathf.cpp"
#include "EngineBase/Input.cpp"
#include "EngineBase/Window.cpp"
#include "EngineBase/Scene.cpp"
#include "EngineBase/Behaviour.cpp"
#include "EngineBase/EventHandler.cpp"
#include "EngineBase/WindowDrawer.cpp"
#include "EngineBase/Transform.cpp"
#include "EngineBase/LinkedList.cpp"
#include "EngineBase/SceneManager.cpp"
#include "EngineBase/Application.cpp"
#include "EngineBase/Mesh.cpp"
#include "EngineBase/MeshRenderer.cpp"

#include "BehaviourScripts/SceneCamera.hpp"
#include "BehaviourScripts/RotateWithTime.hpp"
